spring:
  profiles:
    default: prod
  application:
    name: ChronoScope-Backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.ni0.team/realms/ni0
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
  writer-with-order-by-keys: true

logging:
  level:
    de.ni0.chronoscope: INFO

cors:
  allowed-origins: []
