logging:
  level:
    de.ni0.chronoscope: DEBUG

cors:
  allowed-origins:
    - "*"

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1

chronoscope:
  dev-auth:
    token: local-test-user
    subject: local-test-user
    organizations:
      - private
      - chronoscope-local
    groups:
      - /org-admin/chronoscope-local

keycloak:
  url: https://auth.ni0.team
  realm: ni0
  client-id: chronoscope-admin
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
