package de.ni0.chronoscope.algorithm;

import de.ni0.chronoscope.model.StaticTask;
import org.dmfs.rfc5545.DateTime;
import org.dmfs.rfc5545.recur.InvalidRecurrenceRuleException;
import org.dmfs.rfc5545.recur.RecurrenceRule;
import org.dmfs.rfc5545.recurrenceset.OfRule;
import org.dmfs.rfc5545.recurrenceset.Within;
import org.springframework.stereotype.Component;

import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Expands recurring {@link StaticTask} definitions into concrete {@link BlockedInterval}
 * windows within a planning horizon.
 *
 * <p>Each static task carries a {@code startAt}/{@code endAt} pair that defines the first
 * occurrence and its duration, plus an RFC 5545 {@code rrule} string that governs recurrence.
 * Every occurrence generated by that rule within {@code [now, horizon]} is returned as a
 * blocked interval so that the planner can subtract it from the available work slots.</p>
 *
 * <p>Occurrences that started before {@code now} but have not yet ended are included so that
 * ongoing static tasks correctly block the start of the planning window.</p>
 */
@Component
public class StaticTaskExpander {

    /**
     * Handles basic UTC iCal DTSTART values like {@code 20260518T080000Z}.
     * The trailing offset pattern {@code X} accepts {@code Z} as UTC.
     */
    private static final DateTimeFormatter DTSTART_FORMATTER =
            DateTimeFormatter.ofPattern("yyyyMMdd'T'HHmmssX");

    /**
     * Expands all static tasks into blocked intervals overlapping with {@code [now, horizon]}.
     *
     * @param tasks   static tasks to expand
     * @param now     start of the relevant window (planning cursor)
     * @param horizon end of the planning window
     * @return list of blocked intervals that overlap with {@code [now, horizon]}
     */
    public List<BlockedInterval> expand(List<StaticTask> tasks, Instant now, Instant horizon) {
        List<BlockedInterval> result = new ArrayList<>();
        for (StaticTask task : tasks) {
            expandTask(task, now, horizon, result);
        }
        return result;
    }

    private void expandTask(StaticTask task, Instant now, Instant horizon, List<BlockedInterval> result) {
        Duration occurrenceDuration = Duration.between(task.getStartAt(), task.getEndAt());
        if (!occurrenceDuration.isPositive()) {
            return;
        }

        String rruleValue = task.getRrule();

        // Empty rrule: the task is a single one-time event at startAt–endAt.
        if (rruleValue == null || rruleValue.isBlank()) {
            if (task.getEndAt().isAfter(now) && task.getStartAt().isBefore(horizon)) {
                result.add(new BlockedInterval(task.getStartAt(), task.getEndAt()));
            }
            return;
        }

        // Parse the rrule field.  The frontend may send the full iCal property format:
        //   "DTSTART:20260518T080000Z\nRRULE:FREQ=DAILY;INTERVAL=1;UNTIL=20260523T220000Z"
        // or a plain rule value:
        //   "FREQ=DAILY;INTERVAL=1;UNTIL=20260523T220000Z"
        // Both are supported.  A "RRULE:" prefix on a single line is also stripped.
        String ruleStr = null;
        DateTime dtstart = new DateTime(task.getStartAt().toEpochMilli());

        for (String line : rruleValue.split("\\n")) {
            String trimmedLine = line.trim();
            if (trimmedLine.startsWith("DTSTART:")) {
                String dtStartValue = trimmedLine.substring("DTSTART:".length()).trim();
                try {
                    OffsetDateTime odt = OffsetDateTime.parse(dtStartValue, DTSTART_FORMATTER);
                    dtstart = new DateTime(odt.toInstant().toEpochMilli());
                } catch (Exception e) {
                    // Non-UTC or unrecognised DTSTART format: keep task.getStartAt() as fallback.
                }
            } else if (trimmedLine.startsWith("RRULE:")) {
                ruleStr = trimmedLine.substring("RRULE:".length()).trim();
            }
        }

        // If no "RRULE:" line was found, treat the entire string as a plain rule value.
        if (ruleStr == null) {
            ruleStr = rruleValue.trim();
        }

        RecurrenceRule rule;
        try {
            rule = new RecurrenceRule(ruleStr);
        } catch (InvalidRecurrenceRuleException e) {
            throw new IllegalArgumentException(
                    "Invalid rrule for static task id=" + task.getId() + ": " + task.getRrule(), e);
        }

        // Look back by occurrenceDuration from now so we catch occurrences that started
        // before now but are still ongoing (and therefore still blocking).
        DateTime lookback = new DateTime(now.minus(occurrenceDuration).toEpochMilli());
        DateTime horizonDt = new DateTime(horizon.toEpochMilli());

        // Within iterates occurrences in [lookback, horizonDt); FastForwarded skips
        // past occurrences before lookback, Preceding stops at horizonDt.
        for (DateTime occurrence : new Within(lookback, horizonDt, new OfRule(rule, dtstart))) {
            Instant occStart = Instant.ofEpochMilli(occurrence.getTimestamp());
            Instant occEnd = occStart.plus(occurrenceDuration);
            // Keep only occurrences whose end is strictly after now (they overlap with [now, horizon]).
            if (occEnd.isAfter(now)) {
                result.add(new BlockedInterval(occStart, occEnd));
            }
        }
    }
}
